Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x

In [ ]:
import numpy as np

In [ ]:
x = int(input())
array = np.random.randint(0,x,20)
print(array)

20
[ 4 14 16 13 14 19  9 14  7 16 19  8 10 13  0 16  0  0 11  4]


Write a code that creates a 4x5 array inwhich numbers ranging between 300 and 500 such that the difference between elements is 10

In [ ]:
array = np.arange(300,500,10)
print("array having  300 and 500 " ,array)
array = array.reshape(4,5)
print(array)

array having  300 and 500  [300 310 320 330 340 350 360 370 380 390 400 410 420 430 440 450 460 470
 480 490]
[[300 310 320 330 340]
 [350 360 370 380 390]
 [400 410 420 430 440]
 [450 460 470 480 490]]


Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values

In [ ]:


array = np.random.randint(-1000,1000,[20,20])
print(array)

[[-415  218 -119  -67 -887  423 -540   28  877 -700  526 -549 -484 -439
  -589  503 -428  511 -610  230]
 [ 644 -559  354 -977 -307  890  843  540  329  203 -848 -328 -407 -989
    46  147  871 -753  672  682]
 [ 344    1  766  899 -944  299    2 -783 -714  286  170 -866    7  -41
   306 -748  -88  990 -512 -772]
 [ -94  709 -126 -137 -520  207  755  341 -438  430 -927 -995 -812  677
  -961 -826  849  482  884  526]
 [-128  -63 -244  664  234 -248 -828  447 -858 -822  237  514 -129   42
  -279 -437  276  215 -102  -33]
 [  76  188  -16  764  469 -111  -22 -836   38 -662 -911  183  756  108
   279   10 -644 -893 -392  660]
 [-580 -893  803 -873  946  858 -743   95 -392  679  766  959 -371  104
   841 -707  807  -61  365 -568]
 [-795 -985  -30  -94 -212 -126  249 -688  651   25 -693  425  -71  625
   856 -224  778 -973 -207  999]
 [-354  286 -909 -994  607  799  225  974  118 -115  547 -559 -115 -855
  -255 -872 -160 -491 -444 -992]
 [ 370 -803  916 -800  -75 -742 -534  873 -414 -491  -9

In the following matrix, replace the last row with -1 Multiply the 2x2 matrix in the upper right corner by 2 X = [2 30 20 -2 -4] [3 4 40 -3 -2] [-3 4 -6 90 10] [25 45 34 22 12] [13 24 22 32 37]

In [ ]:
arr = np.array([[2,30,20,-2,-4],[3,4,40,-3,-2],[-3,4,-6,90,10],[25,45,34,22,12],[13,24,22,32,37]])
arr[-1: , :] = -1
arr[:2,3:] *= 2
print(arr)

[[ 2 30 20 -4 -8]
 [ 3  4 40 -6 -4]
 [-3  4 -6 90 10]
 [25 45 34 22 12]
 [-1 -1 -1 -1 -1]]


In the following matrix, replace negative elements by 0 and replace odd elements with 25 X = [2 30 20 -2 -4] [3 4 40 -3 -2] [-3 4 -6 90 10] [25 45 34 22 12] [13 24 22 32 37]


In [ ]:
arr = np.array([[2,30,20,-2,-4],[3,4,40,-3,-2],[-3,4,-6,90,10],[25,45,34,22,12],[13,24,22,32,37]])

arr[np.mod(arr,2) != 0] = -1


arr[arr < 0] = -1
print(arr)


[[ 2 30 20 -1 -1]
 [-1  4 40 -1 -1]
 [-1  4 -1 90 10]
 [-1 -1 34 22 12]
 [-1 24 22 32 -1]]


In [ ]:
print(2%5)

2
